name = "speed"
main = "src/entry-v1.1.js"
compatibility_date = "2026-07-28"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "CURATOR_SPEED_RECORDS"
id = "6de4740a91b94f9a945ce12a9f5a2208"

[triggers]
crons = ["37 * * * *"]

[observability]
enabled = true
